"""add cleaned_text to documents

Revision ID: a834727920d5
Revises: ea2d9f304f2b
Create Date: 2026-04-23 12:36:16.092677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a834727920d5'
down_revision: Union[str, Sequence[str], None] = 'ea2d9f304f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cleaned_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'cleaned_text')
    # ### end Alembic commands ###
